=== mongodb/specifications/source/unified-test-format/schema-1.1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "title": "Unified Test Format",
  "type": "object",
  "additionalProperties": false,
  "required": ["description", "schemaVersion", "tests"],
  "properties": {
    "description": { "type": "string" },
    "schemaVersion": { "$ref": "#/definitions/version" },
    "runOnRequirements": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/runOnRequirement" }
    },
    "createEntities": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/entity" }
    },
    "initialData": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/collectionData" }
    },
    "tests": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/test" }
    },
    "_yamlAnchors": {
      "type": "object",
      "additionalProperties": true
    }
  },

  "definitions": {
    "version": {
      "type": "string",
      "pattern": "^[0-9]+(\\.[0-9]+){1,2}$"
    },

    "runOnRequirement": {
      "type": "object",
      "additionalProperties": false,
      "minProperties": 1,
      "properties": {
        "maxServerVersion": { "$ref": "#/definitions/version" },
        "minServerVersion": { "$ref": "#/definitions/version" },
        "topologies": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "enum": ["single", "replicaset", "sharded", "sharded-replicaset"]
          }
        },
        "serverParameters": {
          "type": "object",
          "minProperties": 1
        }
      }
    },

    "entity": {
      "type": "object",
      "additionalProperties": false,
      "maxProperties": 1,
      "minProperties": 1,
      "properties": {
        "client": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id"],
          "properties": {
            "id": { "type": "string" },
            "uriOptions": { "type": "object" },
            "useMultipleMongoses": { "type": "boolean" },
            "observeEvents": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string",
                "enum": ["commandStartedEvent", "commandSucceededEvent", "commandFailedEvent"]
              }
            },
            "ignoreCommandMonitoringEvents": {
              "type": "array",
              "minItems": 1,
              "items": { "type": "string" }
            },
            "serverApi": { "$ref":  "#/definitions/serverApi" }
          }
        },
        "database": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "client", "databaseName"],
          "properties": {
            "id": { "type": "string" },
            "client": { "type": "string" },
            "databaseName": { "type": "string" },
            "databaseOptions": { "$ref": "#/definitions/collectionOrDatabaseOptions" }
          }
        },
        "collection": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "database", "collectionName"],
          "properties": {
            "id": { "type": "string" },
            "database": { "type": "string" },
            "collectionName": { "type": "string" },
            "collectionOptions": { "$ref": "#/definitions/collectionOrDatabaseOptions" }
          }
        },
        "session": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "client"],
          "properties": {
            "id": { "type": "string" },
            "client": { "type": "string" },
            "sessionOptions": { "type": "object" }
          }
        },
        "bucket": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "database"],
          "properties": {
            "id": { "type": "string" },
            "database": { "type": "string" },
            "bucketOptions": { "type": "object" }
          }
        },
        "stream": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "hexBytes"],
          "properties": {
            "id": { "type": "string" },
            "hexBytes": {
              "type": "string",
              "pattern": "^([0-9A-Fa-f]{2})*$"
            }
          }
        }
      }
    },

    "collectionData": {
      "type": "object",
      "additionalProperties": false,
      "required": ["collectionName", "databaseName", "documents"],
      "properties": {
        "collectionName": { "type": "string" },
        "databaseName": { "type": "string" },
        "documents": {
          "type": "array",
          "items": { "type": "object" }
        }
      }
    },

    "expectedEventsForClient": {
      "type": "object",
      "additionalProperties": false,
      "required": ["client", "events"],
      "properties": {
        "client": { "type": "string" },
        "events": {
          "type": "array",
          "items": { "$ref": "#/definitions/expectedEvent" }
        }
      }
    },

    "expectedEvent": {
      "type": "object",
      "additionalProperties": false,
      "maxProperties": 1,
      "minProperties": 1,
      "properties": {
        "commandStartedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "command": { "type": "object" },
            "commandName": { "type": "string" },
            "databaseName": { "type": "string" }
          }
        },
        "commandSucceededEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "reply": { "type": "object" },
            "commandName": { "type": "string" }
          }
        },
        "commandFailedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "commandName": { "type": "string" }
          }
        }
      }
    },

    "collectionOrDatabaseOptions": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "readConcern": { "type": "object" },
        "readPreference": { "type": "object" },
        "writeConcern": { "type": "object" }
      }
    },

    "serverApi": {
      "type": "object",
      "additionalProperties": false,
      "required": ["version"],
      "properties": {
        "version": { "type": "string" },
        "strict": { "type":  "boolean" },
        "deprecationErrors": { "type":  "boolean" }
      }
    },

    "operation": {
      "type": "object",
      "additionalProperties": false,
      "required": ["name", "object"],
      "properties": {
        "name": { "type": "string" },
        "object": { "type": "string" },
        "arguments": { "type": "object" },
        "expectError":  { "$ref": "#/definitions/expectedError" },
        "expectResult": {},
        "saveResultAsEntity": { "type": "string" }
      },
      "allOf": [
        { "not": { "required": ["expectError", "expectResult"] } },
        { "not": { "required": ["expectError", "saveResultAsEntity"] } }
      ]
    },

    "expectedError": {
      "type": "object",
      "additionalProperties": false,
      "minProperties": 1,
      "properties": {
        "isError": {
          "type": "boolean",
          "const": true
        },
        "isClientError": { "type": "boolean" },
        "errorContains": { "type": "string" },
        "errorCode": { "type": "integer" },
        "errorCodeName": { "type": "string" },
        "errorLabelsContain": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "errorLabelsOmit": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "expectResult": {}
      }
    },

    "test": {
      "type": "object",
      "additionalProperties": false,
      "required": ["description", "operations"],
      "properties": {
        "description": { "type": "string" },
        "runOnRequirements": {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#/definitions/runOnRequirement" }
        },
        "skipReason": { "type": "string" },
        "operations": {
          "type": "array",
          "items": { "$ref": "#/definitions/operation" }
        },
        "expectEvents": {
          "type": "array",
          "items": { "$ref": "#/definitions/expectedEventsForClient" }
        },
        "outcome": {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#/definitions/collectionData" }
        }
      }
    }
  }
}

=== mongodb/specifications/source/crud/tests/unified/deleteMany-comment.json
{
  "description": "deleteMany-comment",
  "schemaVersion": "1.0",
  "runOnRequirements": [
    {
      "minServerVersion": "4.4"
    }
  ],
  "createEntities": [
    {
      "client": {
        "id": "client0",
        "observeEvents": [
          "commandStartedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "crud-tests"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "coll0"
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "coll0",
      "databaseName": "crud-tests",
      "documents": [
        {
          "_id": 1
        },
        {
          "_id": 2
        }
      ]
    }
  ],
  "tests": [
    {
      "description": "deleteMany with string comment",
      "operations": [
        {
          "name": "deleteMany",
          "object": "collection0",
          "arguments": {
            "filter": {
              "_id": 1
            },
            "comment": "comment"
          },
          "expectResult": {
            "deletedCount": 1
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "delete": "coll0",
                  "deletes": [
                    {
                      "q": {
                        "_id": 1
                      }
                    }
                  ],
                  "comment": "comment"
                }
              }
            }
          ]
        }
      ],
      "outcome": [
        {
          "collectionName": "coll0",
          "databaseName": "crud-tests",
          "documents": [
            {
              "_id": 2
            }
          ]
        }
      ]
    },
    {
      "description": "deleteMany with document comment",
      "operations": [
        {
          "name": "deleteMany",
          "object": "collection0",
          "arguments": {
            "filter": {
              "_id": 1
            },
            "comment": {
              "key": "value"
            }
          },
          "expectResult": {
            "deletedCount": 1
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "delete": "coll0",
                  "deletes": [
                    {
                      "q": {
                        "_id": 1
                      }
                    }
                  ],
                  "comment": {
                    "key": "value"
                  }
                }
              }
            }
          ]
        }
      ],
      "outcome": [
        {
          "collectionName": "coll0",
          "databaseName": "crud-tests",
          "documents": [
            {
              "_id": 2
            }
          ]
        }
      ]
    }
  ]
}

=== mongodb/specifications/source/unified-test-format/tests/valid-pass/createEntities-operation.json
{
  "description": "createEntities-operation",
  "schemaVersion": "1.8",
  "createEntities": [
    {
      "client": {
        "id": "client0"
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "database0"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "collection0"
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "collection0",
      "databaseName": "database0",
      "documents": []
    }
  ],
  "tests": [
    {
      "description": "createEntities operation",
      "operations": [
        {
          "name": "createEntities",
          "object": "testRunner",
          "arguments": {
            "entities": [
              {
                "client": {
                  "id": "client1",
                  "observeEvents": [
                    "commandStartedEvent"
                  ]
                }
              },
              {
                "database": {
                  "id": "database1",
                  "client": "client1",
                  "databaseName": "database1"
                }
              },
              {
                "collection": {
                  "id": "collection1",
                  "database": "database1",
                  "collectionName": "collection1"
                }
              }
            ]
          }
        },
        {
          "name": "deleteOne",
          "object": "collection1",
          "arguments": {
            "filter": {
              "_id": 1
            }
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client1",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "delete": "collection1",
                  "deletes": [
                    {
                      "q": {
                        "_id": 1
                      },
                      "limit": 1
                    }
                  ]
                },
                "commandName": "delete",
                "databaseName": "database1"
              }
            }
          ]
        }
      ]
    }
  ]
}

=== mongodb/specifications/source/crud/tests/unified/updateOne-comment.json
{
  "description": "updateOne-comment",
  "schemaVersion": "1.0",
  "runOnRequirements": [
    {
      "minServerVersion": "4.4"
    }
  ],
  "createEntities": [
    {
      "client": {
        "id": "client0",
        "observeEvents": [
          "commandStartedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "crud-tests"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "coll0"
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "coll0",
      "databaseName": "crud-tests",
      "documents": [
        {
          "_id": 1,
          "x": 11
        }
      ]
    }
  ],
  "tests": [
    {
      "description": "UpdateOne with string comment",
      "operations": [
        {
          "name": "updateOne",
          "object": "collection0",
          "arguments": {
            "filter": {
              "_id": 1
            },
            "update": {
              "x": 22
            },
            "comment": "comment"
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "update": "coll0",
                  "updates": [
                    {
                      "q": {
                        "_id": 1
                      },
                      "u": {
                        "x": 22
                      }
                    }
                  ],
                  "comment": "comment"
                }
              }
            }
          ]
        }
      ]
    },
    {
      "description": "UpdateOne with document comment",
      "operations": [
        {
          "name": "updateOne",
          "object": "collection0",
          "arguments": {
            "filter": {
              "_id": 1
            },
            "update": {
              "x": 22
            },
            "comment": {
              "key": "value"
            }
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "update": "coll0",
                  "updates": [
                    {
                      "q": {
                        "_id": 1
                      },
                      "u": {
                        "x": 22
                      }
                    }
                  ],
                  "comment": {
                    "key": "value"
                  }
                }
              }
            }
          ]
        }
      ]
    }
  ]
}

=== mongodb/specifications/source/crud/tests/unified/estimatedDocumentCount.json
{
    "description": "estimatedDocumentCount",
    "schemaVersion": "1.1",
    "createEntities": [
        {
            "client": {
                "id": "client0",
                "observeEvents": [
                    "commandStartedEvent"
                ]
            }
        },
        {
            "database": {
                "id": "database0",
                "client": "client0",
                "databaseName": "edc-tests"
            }
        },
        {
            "collection": {
                "id": "collection0",
                "database": "database0",
                "collectionName": "coll0"
            }
        }
    ],
    "initialData": [
        {
            "collectionName": "coll0",
            "databaseName": "edc-tests",
            "documents": [
                {
                    "_id": 1,
                    "x": 11
                },
                {
                    "_id": 2,
                    "x": 22
                },
                {
                    "_id": 3,
                    "x": 33
                }
            ]
        }
    ],
    "tests": [
        {
            "description": "estimatedDocumentCount uses $collStats on 4.9.0 or greater",
            "runOnRequirements": [
                {
                    "minServerVersion": "4.9.0"
                }
            ],
            "operations": [
                {
                    "name": "estimatedDocumentCount",
                    "object": "collection0",
                    "expectResult": 3
                }
            ],
            "expectEvents": [
                {
                    "client": "client0",
                    "events": [
                        {
                            "commandStartedEvent": {
                                "command": {
                                    "aggregate": "coll0",
                                    "pipeline": [
                                        {
                                            "$collStats": {
                                                "count": {
                                                    "": null
                                                }
                                            }
                                        },
                                        {
                                            "$group": {
                                                "_id": 1,
                                                "n": {
                                                    "$sum": "$count"
                                                }
                                            }
                                        }
                                    ]
                                },
                                "commandName": "aggregate",
                                "databaseName": "edc-tests"
                            }
                        }
                    ]
                }
            ]
        },
        {
            "description": "estimatedDocumentCount with maxTimeMS on 4.9.0 or greater",
            "runOnRequirements": [
                {
                    "minServerVersion": "4.9.0"
                }
            ],
            "operations": [
                {
                    "name": "estimatedDocumentCount",
                    "object": "collection0",
                    "arguments": {
                        "maxTimeMS": 6000
                    },
                    "expectResult": 3
                }
            ],
            "expectEvents": [
                {
                    "client": "client0",
                    "events": [
                        {
                            "commandStartedEvent": {
                                "command": {
                                    "aggregate": "coll0",
                                    "pipeline": [
                                        {
                                            "$collStats": {
                                                "count": {
                                                    "": null
                                                }
                                            }
                                        },
                                        {
                                            "$group": {
                                                "_id": 1,
                                                "n": {
                                                    "$sum": "$count"
                                                }
                                            }
                                        }
                                    ],
                                    "maxTimeMS": 6000
                                },
                                "commandName": "aggregate",
                                "databaseName": "edc-tests"
                            }
                        }
                    ]
                }
            ]
        },
        {
            "description": "estimatedDocumentCount uses count on less than 4.9.0",
            "runOnRequirements": [
                {
                    "maxServerVersion": "4.8.99"
                }
            ],
            "operations": [
                {
                    "name": "estimatedDocumentCount",
                    "object": "collection0",
                    "expectResult": 3
                }
            ],
            "expectEvents": [
                {
                    "client": "client0",
                    "events": [
                        {
                            "commandStartedEvent": {
                                "command": {
                                    "count": "coll0"
                                },
                                "commandName": "count",
                                "databaseName": "edc-tests"
                            }
                        }
                    ]
                }
            ]
        },
        {
            "description": "estimatedDocumentCount with maxTimeMS on less than 4.9.0",
            "runOnRequirements": [
                {
                    "maxServerVersion": "4.8.99"
                }
            ],
            "operations": [
                {
                    "name": "estimatedDocumentCount",
                    "object": "collection0",
                    "arguments": {
                        "maxTimeMS": 6000
                    },
                    "expectResult": 3
                }
            ],
            "expectEvents": [
                {
                    "client": "client0",
                    "events": [
                        {
                            "commandStartedEvent": {
                                "command": {
                                    "count": "coll0",
                                    "maxTimeMS": 6000
                                },
                                "commandName": "count",
                                "databaseName": "edc-tests"
                            }
                        }
                    ]
                }
            ]
        }
    ]
}
