=== mongodb/specifications/source/unified-test-format/schema-1.1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "title": "Unified Test Format",
  "type": "object",
  "additionalProperties": false,
  "required": ["description", "schemaVersion", "tests"],
  "properties": {
    "description": { "type": "string" },
    "schemaVersion": { "$ref": "#/definitions/version" },
    "runOnRequirements": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/runOnRequirement" }
    },
    "createEntities": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/entity" }
    },
    "initialData": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/collectionData" }
    },
    "tests": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/test" }
    },
    "_yamlAnchors": {
      "type": "object",
      "additionalProperties": true
    }
  },

  "definitions": {
    "version": {
      "type": "string",
      "pattern": "^[0-9]+(\\.[0-9]+){1,2}$"
    },

    "runOnRequirement": {
      "type": "object",
      "additionalProperties": false,
      "minProperties": 1,
      "properties": {
        "maxServerVersion": { "$ref": "#/definitions/version" },
        "minServerVersion": { "$ref": "#/definitions/version" },
        "topologies": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "enum": ["single", "replicaset", "sharded", "sharded-replicaset"]
          }
        },
        "serverParameters": {
          "type": "object",
          "minProperties": 1
        }
      }
    },

    "entity": {
      "type": "object",
      "additionalProperties": false,
      "maxProperties": 1,
      "minProperties": 1,
      "properties": {
        "client": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id"],
          "properties": {
            "id": { "type": "string" },
            "uriOptions": { "type": "object" },
            "useMultipleMongoses": { "type": "boolean" },
            "observeEvents": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string",
                "enum": ["commandStartedEvent", "commandSucceededEvent", "commandFailedEvent"]
              }
            },
            "ignoreCommandMonitoringEvents": {
              "type": "array",
              "minItems": 1,
              "items": { "type": "string" }
            },
            "serverApi": { "$ref":  "#/definitions/serverApi" }
          }
        },
        "database": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "client", "databaseName"],
          "properties": {
            "id": { "type": "string" },
            "client": { "type": "string" },
            "databaseName": { "type": "string" },
            "databaseOptions": { "$ref": "#/definitions/collectionOrDatabaseOptions" }
          }
        },
        "collection": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "database", "collectionName"],
          "properties": {
            "id": { "type": "string" },
            "database": { "type": "string" },
            "collectionName": { "type": "string" },
            "collectionOptions": { "$ref": "#/definitions/collectionOrDatabaseOptions" }
          }
        },
        "session": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "client"],
          "properties": {
            "id": { "type": "string" },
            "client": { "type": "string" },
            "sessionOptions": { "type": "object" }
          }
        },
        "bucket": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "database"],
          "properties": {
            "id": { "type": "string" },
            "database": { "type": "string" },
            "bucketOptions": { "type": "object" }
          }
        },
        "stream": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "hexBytes"],
          "properties": {
            "id": { "type": "string" },
            "hexBytes": {
              "type": "string",
              "pattern": "^([0-9A-Fa-f]{2})*$"
            }
          }
        }
      }
    },

    "collectionData": {
      "type": "object",
      "additionalProperties": false,
      "required": ["collectionName", "databaseName", "documents"],
      "properties": {
        "collectionName": { "type": "string" },
        "databaseName": { "type": "string" },
        "documents": {
          "type": "array",
          "items": { "type": "object" }
        }
      }
    },

    "expectedEventsForClient": {
      "type": "object",
      "additionalProperties": false,
      "required": ["client", "events"],
      "properties": {
        "client": { "type": "string" },
        "events": {
          "type": "array",
          "items": { "$ref": "#/definitions/expectedEvent" }
        }
      }
    },

    "expectedEvent": {
      "type": "object",
      "additionalProperties": false,
      "maxProperties": 1,
      "minProperties": 1,
      "properties": {
        "commandStartedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "command": { "type": "object" },
            "commandName": { "type": "string" },
            "databaseName": { "type": "string" }
          }
        },
        "commandSucceededEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "reply": { "type": "object" },
            "commandName": { "type": "string" }
          }
        },
        "commandFailedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "commandName": { "type": "string" }
          }
        }
      }
    },

    "collectionOrDatabaseOptions": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "readConcern": { "type": "object" },
        "readPreference": { "type": "object" },
        "writeConcern": { "type": "object" }
      }
    },

    "serverApi": {
      "type": "object",
      "additionalProperties": false,
      "required": ["version"],
      "properties": {
        "version": { "type": "string" },
        "strict": { "type":  "boolean" },
        "deprecationErrors": { "type":  "boolean" }
      }
    },

    "operation": {
      "type": "object",
      "additionalProperties": false,
      "required": ["name", "object"],
      "properties": {
        "name": { "type": "string" },
        "object": { "type": "string" },
        "arguments": { "type": "object" },
        "expectError":  { "$ref": "#/definitions/expectedError" },
        "expectResult": {},
        "saveResultAsEntity": { "type": "string" }
      },
      "allOf": [
        { "not": { "required": ["expectError", "expectResult"] } },
        { "not": { "required": ["expectError", "saveResultAsEntity"] } }
      ]
    },

    "expectedError": {
      "type": "object",
      "additionalProperties": false,
      "minProperties": 1,
      "properties": {
        "isError": {
          "type": "boolean",
          "const": true
        },
        "isClientError": { "type": "boolean" },
        "errorContains": { "type": "string" },
        "errorCode": { "type": "integer" },
        "errorCodeName": { "type": "string" },
        "errorLabelsContain": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "errorLabelsOmit": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "expectResult": {}
      }
    },

    "test": {
      "type": "object",
      "additionalProperties": false,
      "required": ["description", "operations"],
      "properties": {
        "description": { "type": "string" },
        "runOnRequirements": {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#/definitions/runOnRequirement" }
        },
        "skipReason": { "type": "string" },
        "operations": {
          "type": "array",
          "items": { "$ref": "#/definitions/operation" }
        },
        "expectEvents": {
          "type": "array",
          "items": { "$ref": "#/definitions/expectedEventsForClient" }
        },
        "outcome": {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#/definitions/collectionData" }
        }
      }
    }
  }
}

=== mongodb/specifications/source/unified-test-format/tests/valid-pass/entity-runCursorCommand.json
{
  "description": "runCursorCommand",
  "schemaVersion": "1.3",
  "createEntities": [
    {
      "client": {
        "id": "client",
        "useMultipleMongoses": false,
        "observeEvents": [
          "commandStartedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "db",
        "client": "client",
        "databaseName": "db"
      }
    },
    {
      "collection": {
        "id": "collection",
        "database": "db",
        "collectionName": "collection"
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "collection",
      "databaseName": "db",
      "documents": [
        {
          "_id": 1,
          "x": 11
        },
        {
          "_id": 2,
          "x": 22
        },
        {
          "_id": 3,
          "x": 33
        },
        {
          "_id": 4,
          "x": 44
        },
        {
          "_id": 5,
          "x": 55
        }
      ]
    }
  ],
  "tests": [
    {
      "description": "creates a cursor and iterates results from getMores",
      "operations": [
        {
          "name": "runCursorCommand",
          "object": "db",
          "arguments": {
            "commandName": "find",
            "batchSize": 2,
            "command": {
              "find": "collection",
              "filter": {},
              "batchSize": 2
            }
          },
          "expectResult": [
            {
              "_id": 1,
              "x": 11
            },
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            },
            {
              "_id": 4,
              "x": 44
            },
            {
              "_id": 5,
              "x": 55
            }
          ]
        }
      ],
      "expectEvents": [
        {
          "client": "client",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "collection",
                  "filter": {},
                  "batchSize": 2,
                  "$db": "db",
                  "lsid": {
                    "id": {
                      "$$type": "binData"
                    }
                  }
                },
                "commandName": "find"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "getMore": {
                    "$$type": "long"
                  },
                  "collection": "collection",
                  "$db": "db",
                  "lsid": {
                    "id": {
                      "$$type": "binData"
                    }
                  }
                },
                "commandName": "getMore"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "getMore": {
                    "$$type": "long"
                  },
                  "collection": "collection",
                  "$db": "db",
                  "lsid": {
                    "id": {
                      "$$type": "binData"
                    }
                  }
                },
                "commandName": "getMore"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "creates a cursor and iterates one result at a time",
      "operations": [
        {
          "name": "createRunCursorCommand",
          "object": "db",
          "arguments": {
            "commandName": "find",
            "batchSize": 2,
            "command": {
              "find": "collection",
              "filter": {},
              "batchSize": 2
            }
          },
          "saveResultAsEntity": "myRunCommandCursor"
        },
        {
          "name": "iterateUntilDocumentOrError",
          "object": "myRunCommandCursor",
          "expectResult": {
            "_id": 1,
            "x": 11
          }
        },
        {
          "name": "iterateUntilDocumentOrError",
          "object": "myRunCommandCursor",
          "expectResult": {
            "_id": 2,
            "x": 22
          }
        },
        {
          "name": "iterateUntilDocumentOrError",
          "object": "myRunCommandCursor",
          "expectResult": {
            "_id": 3,
            "x": 33
          }
        },
        {
          "name": "iterateUntilDocumentOrError",
          "object": "myRunCommandCursor",
          "expectResult": {
            "_id": 4,
            "x": 44
          }
        },
        {
          "name": "iterateUntilDocumentOrError",
          "object": "myRunCommandCursor",
          "expectResult": {
            "_id": 5,
            "x": 55
          }
        }
      ]
    },
    {
      "description": "closing a runCursorCommand entity causes a killCursors operation",
      "operations": [
        {
          "name": "createRunCursorCommand",
          "object": "db",
          "arguments": {
            "commandName": "find",
            "batchSize": 2,
            "command": {
              "find": "collection",
              "filter": {},
              "batchSize": 2
            }
          },
          "saveResultAsEntity": "myRunCommandCursor"
        },
        {
          "name": "iterateUntilDocumentOrError",
          "object": "myRunCommandCursor",
          "expectResult": {
            "_id": 1,
            "x": 11
          }
        },
        {
          "name": "close",
          "object": "myRunCommandCursor"
        }
      ],
      "expectEvents": [
        {
          "client": "client",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "collection",
                  "filter": {},
                  "batchSize": 2,
                  "$db": "db",
                  "lsid": {
                    "id": {
                      "$$type": "binData"
                    }
                  }
                },
                "commandName": "find"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "killCursors": "collection",
                  "cursors": [
                    {
                      "$$type": "long"
                    }
                  ]
                },
                "commandName": "killCursors"
              }
            }
          ]
        }
      ]
    }
  ]
}

=== mongodb/specifications/source/crud/tests/unified/bulkWrite-updateMany-hint-unacknowledged.json
{
  "description": "bulkWrite-updateMany-hint-unacknowledged",
  "schemaVersion": "1.0",
  "createEntities": [
    {
      "client": {
        "id": "client0",
        "observeEvents": [
          "commandStartedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "db0"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "coll0",
        "collectionOptions": {
          "writeConcern": {
            "w": 0
          }
        }
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "coll0",
      "databaseName": "db0",
      "documents": [
        {
          "_id": 1,
          "x": 11
        },
        {
          "_id": 2,
          "x": 22
        },
        {
          "_id": 3,
          "x": 33
        }
      ]
    }
  ],
  "tests": [
    {
      "description": "Unacknowledged updateMany with hint string on 4.2+ server",
      "runOnRequirements": [
        {
          "minServerVersion": "4.2.0"
        }
      ],
      "operations": [
        {
          "object": "collection0",
          "name": "bulkWrite",
          "arguments": {
            "requests": [
              {
                "updateMany": {
                  "filter": {
                    "_id": {
                      "$gt": 1
                    }
                  },
                  "update": {
                    "$inc": {
                      "x": 1
                    }
                  },
                  "hint": "_id_"
                }
              }
            ]
          },
          "expectResult": {
            "$$unsetOrMatches": {
              "acknowledged": {
                "$$unsetOrMatches": false
              }
            }
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "update": "coll0",
                  "updates": [
                    {
                      "q": {
                        "_id": {
                          "$gt": 1
                        }
                      },
                      "u": {
                        "$inc": {
                          "x": 1
                        }
                      },
                      "multi": true,
                      "upsert": {
                        "$$unsetOrMatches": false
                      },
                      "hint": {
                        "$$type": [
                          "string",
                          "object"
                        ]
                      }
                    }
                  ],
                  "writeConcern": {
                    "w": 0
                  }
                }
              }
            }
          ]
        }
      ]
    },
    {
      "description": "Unacknowledged updateMany with hint document on 4.2+ server",
      "runOnRequirements": [
        {
          "minServerVersion": "4.2.0"
        }
      ],
      "operations": [
        {
          "object": "collection0",
          "name": "bulkWrite",
          "arguments": {
            "requests": [
              {
                "updateMany": {
                  "filter": {
                    "_id": {
                      "$gt": 1
                    }
                  },
                  "update": {
                    "$inc": {
                      "x": 1
                    }
                  },
                  "hint": {
                    "_id": 1
                  }
                }
              }
            ]
          },
          "expectResult": {
            "$$unsetOrMatches": {
              "acknowledged": {
                "$$unsetOrMatches": false
              }
            }
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "update": "coll0",
                  "updates": [
                    {
                      "q": {
                        "_id": {
                          "$gt": 1
                        }
                      },
                      "u": {
                        "$inc": {
                          "x": 1
                        }
                      },
                      "multi": true,
                      "upsert": {
                        "$$unsetOrMatches": false
                      },
                      "hint": {
                        "$$type": [
                          "string",
                          "object"
                        ]
                      }
                    }
                  ],
                  "writeConcern": {
                    "w": 0
                  }
                }
              }
            }
          ]
        }
      ]
    }
  ]
}

=== mongodb/specifications/source/crud/tests/unified/insertOne-comment.json
{
  "description": "insertOne-comment",
  "schemaVersion": "1.0",
  "runOnRequirements": [
    {
      "minServerVersion": "4.4"
    }
  ],
  "createEntities": [
    {
      "client": {
        "id": "client0",
        "observeEvents": [
          "commandStartedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "crud-tests"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "coll0"
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "coll0",
      "databaseName": "crud-tests",
      "documents": [
        {
          "_id": 1,
          "x": 11
        }
      ]
    }
  ],
  "tests": [
    {
      "description": "insertOne with string comment",
      "operations": [
        {
          "name": "insertOne",
          "object": "collection0",
          "arguments": {
            "document": {
              "_id": 2,
              "x": 22
            },
            "comment": "comment"
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "insert": "coll0",
                  "documents": [
                    {
                      "_id": 2,
                      "x": 22
                    }
                  ],
                  "comment": "comment"
                }
              }
            }
          ]
        }
      ]
    },
    {
      "description": "insertOne with document comment",
      "operations": [
        {
          "name": "insertOne",
          "object": "collection0",
          "arguments": {
            "document": {
              "_id": 2,
              "x": 22
            },
            "comment": {
              "key": "value"
            }
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "insert": "coll0",
                  "documents": [
                    {
                      "_id": 2,
                      "x": 22
                    }
                  ],
                  "comment": {
                    "key": "value"
                  }
                }
              }
            }
          ]
        }
      ]
    }
  ]
}

=== mongodb/specifications/source/crud/tests/unified/replaceOne-comment.json
{
  "description": "replaceOne-comment",
  "schemaVersion": "1.0",
  "runOnRequirements": [
    {
      "minServerVersion": "4.4"
    }
  ],
  "createEntities": [
    {
      "client": {
        "id": "client0",
        "observeEvents": [
          "commandStartedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "crud-tests"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "coll0"
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "coll0",
      "databaseName": "crud-tests",
      "documents": [
        {
          "_id": 1,
          "x": 11
        }
      ]
    }
  ],
  "tests": [
    {
      "description": "ReplaceOne with string comment",
      "operations": [
        {
          "name": "replaceOne",
          "object": "collection0",
          "arguments": {
            "filter": {
              "_id": 1
            },
            "replacement": {
              "x": 22
            },
            "comment": "comment"
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "update": "coll0",
                  "updates": [
                    {
                      "q": {
                        "_id": 1
                      },
                      "u": {
                        "x": 22
                      }
                    }
                  ],
                  "comment": "comment"
                }
              }
            }
          ]
        }
      ]
    },
    {
      "description": "ReplaceOne with document comment",
      "operations": [
        {
          "name": "replaceOne",
          "object": "collection0",
          "arguments": {
            "filter": {
              "_id": 1
            },
            "replacement": {
              "x": 22
            },
            "comment": {
              "key": "value"
            }
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "update": "coll0",
                  "updates": [
                    {
                      "q": {
                        "_id": 1
                      },
                      "u": {
                        "x": 22
                      }
                    }
                  ],
                  "comment": {
                    "key": "value"
                  }
                }
              }
            }
          ]
        }
      ]
    }
  ]
}

=== mongodb/specifications/source/crud/tests/unified/insertMany-comment.json
{
  "description": "insertMany-comment",
  "schemaVersion": "1.0",
  "runOnRequirements": [
    {
      "minServerVersion": "4.4"
    }
  ],
  "createEntities": [
    {
      "client": {
        "id": "client0",
        "observeEvents": [
          "commandStartedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "crud-tests"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "coll0"
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "coll0",
      "databaseName": "crud-tests",
      "documents": [
        {
          "_id": 1,
          "x": 11
        }
      ]
    }
  ],
  "tests": [
    {
      "description": "insertMany with string comment",
      "operations": [
        {
          "name": "insertMany",
          "object": "collection0",
          "arguments": {
            "documents": [
              {
                "_id": 2,
                "x": 22
              }
            ],
            "comment": "comment"
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "insert": "coll0",
                  "documents": [
                    {
                      "_id": 2,
                      "x": 22
                    }
                  ],
                  "comment": "comment"
                }
              }
            }
          ]
        }
      ]
    },
    {
      "description": "insertMany with document comment",
      "operations": [
        {
          "name": "insertMany",
          "object": "collection0",
          "arguments": {
            "documents": [
              {
                "_id": 2,
                "x": 22
              }
            ],
            "comment": {
              "key": "value"
            }
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "insert": "coll0",
                  "documents": [
                    {
                      "_id": 2,
                      "x": 22
                    }
                  ],
                  "comment": {
                    "key": "value"
                  }
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
