=== mongodb/specifications/source/unified-test-format/schema-1.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "title": "Unified Test Format",
  "type": "object",
  "additionalProperties": false,
  "required": ["description", "schemaVersion", "tests"],
  "properties": {
    "description": { "type": "string" },
    "schemaVersion": { "$ref": "#/definitions/version" },
    "runOnRequirements": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/runOnRequirement" }
    },
    "createEntities": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/entity" }
    },
    "initialData": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/collectionData" }
    },
    "tests": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/test" }
    },
    "_yamlAnchors": {
      "type": "object",
      "additionalProperties": true
    }
  },

  "definitions": {
    "version": {
      "type": "string",
      "pattern": "^[0-9]+(\\.[0-9]+){1,2}$"
    },

    "runOnRequirement": {
      "type": "object",
      "additionalProperties": false,
      "minProperties": 1,
      "properties": {
        "maxServerVersion": { "$ref": "#/definitions/version" },
        "minServerVersion": { "$ref": "#/definitions/version" },
        "topologies": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "enum": ["single", "replicaset", "sharded", "sharded-replicaset", "load-balanced"]
          }
        },
        "serverParameters": {
          "type": "object",
          "minProperties": 1
        },
        "auth": { "type": "boolean" }
      }
    },

    "entity": {
      "type": "object",
      "additionalProperties": false,
      "maxProperties": 1,
      "minProperties": 1,
      "properties": {
        "client": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id"],
          "properties": {
            "id": { "type": "string" },
            "uriOptions": { "type": "object" },
            "useMultipleMongoses": { "type": "boolean" },
            "observeEvents": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string",
                "enum": [
                  "commandStartedEvent",
                  "commandSucceededEvent",
                  "commandFailedEvent",
                  "poolCreatedEvent",
                  "poolReadyEvent",
                  "poolClearedEvent",
                  "poolClosedEvent",
                  "connectionCreatedEvent",
                  "connectionReadyEvent",
                  "connectionClosedEvent",
                  "connectionCheckOutStartedEvent",
                  "connectionCheckOutFailedEvent",
                  "connectionCheckedOutEvent",
                  "connectionCheckedInEvent"
                ]
              }
            },
            "ignoreCommandMonitoringEvents": {
              "type": "array",
              "minItems": 1,
              "items": { "type": "string" }
            },
            "storeEventsAsEntities": {
              "type": "array",
              "minItems": 1,
              "items": { "$ref": "#/definitions/storeEventsAsEntity" }
            },
            "serverApi": { "$ref":  "#/definitions/serverApi" }
          }
        },
        "database": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "client", "databaseName"],
          "properties": {
            "id": { "type": "string" },
            "client": { "type": "string" },
            "databaseName": { "type": "string" },
            "databaseOptions": { "$ref": "#/definitions/collectionOrDatabaseOptions" }
          }
        },
        "collection": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "database", "collectionName"],
          "properties": {
            "id": { "type": "string" },
            "database": { "type": "string" },
            "collectionName": { "type": "string" },
            "collectionOptions": { "$ref": "#/definitions/collectionOrDatabaseOptions" }
          }
        },
        "session": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "client"],
          "properties": {
            "id": { "type": "string" },
            "client": { "type": "string" },
            "sessionOptions": { "type": "object" }
          }
        },
        "bucket": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "database"],
          "properties": {
            "id": { "type": "string" },
            "database": { "type": "string" },
            "bucketOptions": { "type": "object" }
          }
        }
      }
    },

    "storeEventsAsEntity": {
      "type": "object",
      "additionalProperties": false,
      "required": ["id", "events"],
      "properties": {
        "id": { "type": "string" },
        "events": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "enum": [
              "PoolCreatedEvent",
              "PoolReadyEvent",
              "PoolClearedEvent",
              "PoolClosedEvent",
              "ConnectionCreatedEvent",
              "ConnectionReadyEvent",
              "ConnectionClosedEvent",
              "ConnectionCheckOutStartedEvent",
              "ConnectionCheckOutFailedEvent",
              "ConnectionCheckedOutEvent",
              "ConnectionCheckedInEvent",
              "CommandStartedEvent",
              "CommandSucceededEvent",
              "CommandFailedEvent"
            ]
          }
        }
      }
    },

    "collectionData": {
      "type": "object",
      "additionalProperties": false,
      "required": ["collectionName", "databaseName", "documents"],
      "properties": {
        "collectionName": { "type": "string" },
        "databaseName": { "type": "string" },
        "documents": {
          "type": "array",
          "items": { "type": "object" }
        }
      }
    },

    "expectedEventsForClient": {
      "type": "object",
      "additionalProperties": false,
      "required": ["client", "events"],
      "properties": {
        "client": { "type": "string" },
        "eventType": {
          "type": "string",
          "enum": ["command", "cmap"]
        },
        "events": { "type": "array" }
      },
      "oneOf": [
        {
          "required": ["eventType"],
          "properties": {
            "eventType": { "const": "command" },
            "events": {
              "type": "array",
              "items": { "$ref": "#/definitions/expectedCommandEvent" }
            }
          }
        },
        {
          "required": ["eventType"],
          "properties": {
            "eventType": { "const": "cmap" },
            "events": {
              "type": "array",
              "items": { "$ref": "#/definitions/expectedCmapEvent" }
            }
          }
        },
        {
          "additionalProperties": false,
          "properties": {
            "client": { "type": "string" },
            "events": {
              "type": "array",
              "items": { "$ref": "#/definitions/expectedCommandEvent" }
            }
          }
        }
      ]
    },

    "expectedCommandEvent": {
      "type": "object",
      "additionalProperties": false,
      "maxProperties": 1,
      "minProperties": 1,
      "properties": {
        "commandStartedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "command": { "type": "object" },
            "commandName": { "type": "string" },
            "databaseName": { "type": "string" },
            "hasServiceId": { "type": "boolean" }
          }
        },
        "commandSucceededEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "reply": { "type": "object" },
            "commandName": { "type": "string" },
            "hasServiceId": { "type": "boolean" }
          }
        },
        "commandFailedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "commandName": { "type": "string" },
            "hasServiceId": { "type": "boolean" }
          }
        }
      }
    },

    "expectedCmapEvent": {
      "type": "object",
      "additionalProperties": false,
      "maxProperties": 1,
      "minProperties": 1,
      "properties": {
        "poolCreatedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {}
        },
        "poolReadyEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {}
        },
        "poolClearedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "hasServiceId": { "type": "boolean" }
          }
        },
        "poolClosedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {}
        },
        "connectionCreatedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {}
        },
        "connectionReadyEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {}
        },
        "connectionClosedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "reason": { "type": "string" }
          }
        },
        "connectionCheckOutStartedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {}
        },
        "connectionCheckOutFailedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "reason": { "type": "string" }
          }
        },
        "connectionCheckedOutEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {}
        },
        "connectionCheckedInEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {}
        }
      }
    },

    "collectionOrDatabaseOptions": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "readConcern": { "type": "object" },
        "readPreference": { "type": "object" },
        "writeConcern": { "type": "object" }
      }
    },

    "serverApi": {
      "type": "object",
      "additionalProperties": false,
      "required": ["version"],
      "properties": {
        "version": { "type": "string" },
        "strict": { "type":  "boolean" },
        "deprecationErrors": { "type":  "boolean" }
      }
    },

    "operation": {
      "type": "object",
      "additionalProperties": false,
      "required": ["name", "object"],
      "properties": {
        "name": { "type": "string" },
        "object": { "type": "string" },
        "arguments": { "type": "object" },
        "ignoreResultAndError": { "type": "boolean" },
        "expectError":  { "$ref": "#/definitions/expectedError" },
        "expectResult": {},
        "saveResultAsEntity": { "type": "string" }
      },
      "allOf": [
        { "not": { "required": ["expectError", "expectResult"] } },
        { "not": { "required": ["expectError", "saveResultAsEntity"] } },
        { "not": { "required": ["ignoreResultAndError", "expectResult"] } },
        { "not": { "required": ["ignoreResultAndError", "expectError"] } },
        { "not": { "required": ["ignoreResultAndError", "saveResultAsEntity"] } }
      ]
    },

    "expectedError": {
      "type": "object",
      "additionalProperties": false,
      "minProperties": 1,
      "properties": {
        "isError": {
          "type": "boolean",
          "const": true
        },
        "isClientError": { "type": "boolean" },
        "errorContains": { "type": "string" },
        "errorCode": { "type": "integer" },
        "errorCodeName": { "type": "string" },
        "errorLabelsContain": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "errorLabelsOmit": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "expectResult": {}
      }
    },

    "test": {
      "type": "object",
      "additionalProperties": false,
      "required": ["description", "operations"],
      "properties": {
        "description": { "type": "string" },
        "runOnRequirements": {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#/definitions/runOnRequirement" }
        },
        "skipReason": { "type": "string" },
        "operations": {
          "type": "array",
          "items": { "$ref": "#/definitions/operation" }
        },
        "expectEvents": {
          "type": "array",
          "items": { "$ref": "#/definitions/expectedEventsForClient" }
        },
        "outcome": {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#/definitions/collectionData" }
        }
      }
    }
  }
}

=== mongodb/specifications/source/mongodb-handshake/tests/unified/metadata-not-transferred.json
{
  "description": "client metadata is not transferred",
  "schemaVersion": "1.9",
  "runOnRequirements": [
    {
      "minServerVersion": "6.0"
    }
  ],
  "createEntities": [
    {
      "client": {
        "id": "client",
        "observeEvents": [
          "commandSucceededEvent",
          "commandFailedEvent",
          "connectionClosedEvent",
          "connectionCreatedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database",
        "client": "client",
        "databaseName": "test"
      }
    }
  ],
  "tests": [
    {
     "description": "metadata append does not create new connections or close existing ones and no hello command is sent",
      "operations": [
        {
          "name": "runCommand",
          "object": "database",
          "arguments": {
            "command": {
              "ping": 1
            }
          },
          "expectResult": {
            "ok": 1
          }
        },
        {
          "name": "appendClientMetadata",
          "object": "client",
          "arguments": {
            "driverInfoOptions": {
              "name": "framework",
              "version": "2.0",
              "platform": "Framework Platform"
            }
          }
        },
        {
          "name": "runCommand",
          "object": "database",
          "arguments": {
            "command": {
              "ping": 1
            }
          },
          "expectResult": {
            "ok": 1
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client",
          "eventType": "cmap",
          "events": [
            {
              "connectionCreatedEvent": {}
            }
          ]
        },
        {
          "client": "client",
          "eventType": "command",
          "events": [
            {
              "commandSucceededEvent": {
                "commandName": "ping"
              }
            },
            {
              "commandSucceededEvent": {
                "commandName": "ping"
              }
            }
          ]
        }
      ]
    }
  ]
}

=== mongodb/specifications/source/retryable-reads/tests/unified/ExceededTimeLimit.json
{
  "description": "ExceededTimeLimit is a retryable read",
  "schemaVersion": "1.0",
  "runOnRequirements": [
    {
      "minServerVersion": "4.2",
      "topologies": [
        "replicaset",
        "sharded",
        "load-balanced"
      ],
      "auth": true
    }
  ],
  "createEntities": [
    {
      "client": {
        "id": "client0",
        "useMultipleMongoses": false,
        "observeEvents": [
          "commandStartedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "find-tests"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "coll0"
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "coll0",
      "databaseName": "find-tests",
      "documents": [
        {
          "_id": 1,
          "x": 11
        },
        {
          "_id": 2,
          "x": 22
        },
        {
          "_id": 3,
          "x": 33
        },
        {
          "_id": 4,
          "x": 44
        },
        {
          "_id": 5,
          "x": 55
        },
        {
          "_id": 6,
          "x": 66
        }
      ]
    }
  ],
  "tests": [
    {
      "description": "Find succeeds on second attempt after ExceededTimeLimit",
      "operations": [
        {
          "name": "failPoint",
          "object": "testRunner",
          "arguments": {
            "client": "client0",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 1
              },
              "data": {
                "failCommands": [
                  "find"
                ],
                "closeConnection": false,
                "errorCode": 262
              }
            }
          }
        },
        {
          "name": "find",
          "arguments": {
            "filter": {
              "_id": {
                "$gt": 1
              }
            },
            "batchSize": 10
          },
          "object": "collection0",
          "expectResult": [
            {
              "_id": 2,
              "x": 22
            },
            {
              "_id": 3,
              "x": 33
            },
            {
              "_id": 4,
              "x": 44
            },
            {
              "_id": 5,
              "x": 55
            },
            {
              "_id": 6,
              "x": 66
            }
          ]
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll0",
                  "filter": {
                    "_id": {
                      "$gt": 1
                    }
                  },
                  "batchSize": 10
                },
                "commandName": "find",
                "databaseName": "find-tests"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll0",
                  "filter": {
                    "_id": {
                      "$gt": 1
                    }
                  },
                  "batchSize": 10
                },
                "commandName": "find",
                "databaseName": "find-tests"
              }
            }
          ]
        }
      ]
    }
  ]
}

=== mongodb/specifications/source/load-balancers/tests/driver-sessions.json
{
  "description": "driver sessions for load-balanced clusters",
  "schemaVersion": "1.4",
  "runOnRequirements": [
    {
      "topologies": [
        "load-balanced"
      ]
    }
  ],
  "createEntities": [
    {
      "client": {
        "id": "client0",
        "useMultipleMongoses": true,
        "observeEvents": [
          "commandStartedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "database0"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "collection0"
      }
    }
  ],
  "tests": [
    {
      "description": "sessions are always supported with load-balanced topology",
      "operations": [
        {
          "name": "createClientSession",
          "object": "client0",
          "arguments": {},
          "saveResultAsEntity": "session0"
        },
        {
          "name": "insertOne",
          "object": "collection0",
          "arguments": {
            "document": {
              "x": 1
            },
            "session": "session0"
          }
        }
      ]
    },
    {
      "description": "ServerType LoadBalancer is considered a data-bearing server",
      "operations": [
        {
          "name": "createClientSession",
          "object": "client0",
          "arguments": {},
          "saveResultAsEntity": "session1"
        },
        {
          "name": "runCommand",
          "object": "database0",
          "arguments": {
            "commandName": "ping",
            "command": {
              "ping": 1
            },
            "session": "session1"
          }
        },
        {
          "name": "find",
          "object": "collection0",
          "arguments": {
            "filter": {},
            "session": "session1"
          }
        }
      ]
    }
  ]
}

=== mongodb/specifications/source/client-backpressure/tests/backpressure-runCommand-requirements.json
{
  "description": "tests that runCommand only retries when retryReads=true and retryWrites=true",
  "schemaVersion": "1.3",
  "runOnRequirements": [
    {
      "minServerVersion": "4.4",
      "topologies": [
        "replicaset",
        "sharded",
        "load-balanced"
      ]
    }
  ],
  "createEntities": [
    {
      "client": {
        "id": "client_defaults",
        "useMultipleMongoses": false,
        "observeEvents": [
          "commandStartedEvent",
          "commandSucceededEvent",
          "commandFailedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database_defaults",
        "client": "client_defaults",
        "databaseName": "backpressure-runCommand-requirements-db"
      }
    },
    {
      "client": {
        "id": "client_retryReads_false",
        "useMultipleMongoses": false,
        "observeEvents": [
          "commandStartedEvent",
          "commandSucceededEvent",
          "commandFailedEvent"
        ],
        "uriOptions": {
          "retryReads": false
        }
      }
    },
    {
      "database": {
        "id": "database_retryReads_false",
        "client": "client_retryReads_false",
        "databaseName": "backpressure-runCommand-requirements-db"
      }
    },
    {
      "client": {
        "id": "client_retryWrites_false",
        "useMultipleMongoses": false,
        "observeEvents": [
          "commandStartedEvent",
          "commandSucceededEvent",
          "commandFailedEvent"
        ],
        "uriOptions": {
          "retryWrites": false
        }
      }
    },
    {
      "database": {
        "id": "database_retryWrites_false",
        "client": "client_retryWrites_false",
        "databaseName": "backpressure-runCommand-requirements-db"
      }
    },
    {
      "client": {
        "id": "internal_client",
        "useMultipleMongoses": false
      }
    }
  ],
  "tests": [
    {
      "description": "database.runCommand retries with defaults (retryReads=true and retryWrites=true)",
      "operations": [
        {
          "name": "failPoint",
          "object": "testRunner",
          "arguments": {
            "client": "internal_client",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 1
              },
              "data": {
                "failCommands": [
                  "ping"
                ],
                "errorLabels": [
                  "RetryableError",
                  "SystemOverloadedError"
                ],
                "errorCode": 2
              }
            }
          }
        },
        {
          "name": "runCommand",
          "object": "database_defaults",
          "arguments": {
            "command": {
              "ping": 1
            },
            "commandName": "ping"
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client_defaults",
          "events": [
            {
              "commandStartedEvent": {
                "commandName": "ping"
              }
            },
            {
              "commandFailedEvent": {
                "commandName": "ping"
              }
            },
            {
              "commandStartedEvent": {
                "commandName": "ping"
              }
            },
            {
              "commandSucceededEvent": {
                "commandName": "ping"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "database.runCommand does not retry when retryReads=false",
      "operations": [
        {
          "name": "failPoint",
          "object": "testRunner",
          "arguments": {
            "client": "internal_client",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 1
              },
              "data": {
                "failCommands": [
                  "ping"
                ],
                "errorLabels": [
                  "RetryableError",
                  "SystemOverloadedError"
                ],
                "errorCode": 2
              }
            }
          }
        },
        {
          "name": "runCommand",
          "object": "database_retryReads_false",
          "arguments": {
            "command": {
              "ping": 1
            },
            "commandName": "ping"
          },
          "expectError": {
            "isError": true,
            "isClientError": false
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client_retryReads_false",
          "events": [
            {
              "commandStartedEvent": {
                "commandName": "ping"
              }
            },
            {
              "commandFailedEvent": {
                "commandName": "ping"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "database.runCommand does not retry when retryWrites=false",
      "operations": [
        {
          "name": "failPoint",
          "object": "testRunner",
          "arguments": {
            "client": "internal_client",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 1
              },
              "data": {
                "failCommands": [
                  "ping"
                ],
                "errorLabels": [
                  "RetryableError",
                  "SystemOverloadedError"
                ],
                "errorCode": 2
              }
            }
          }
        },
        {
          "name": "runCommand",
          "object": "database_retryWrites_false",
          "arguments": {
            "command": {
              "ping": 1
            },
            "commandName": "ping"
          },
          "expectError": {
            "isError": true,
            "isClientError": false
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client_retryWrites_false",
          "events": [
            {
              "commandStartedEvent": {
                "commandName": "ping"
              }
            },
            {
              "commandFailedEvent": {
                "commandName": "ping"
              }
            }
          ]
        }
      ]
    }
  ]
}
