=== mongodb/specifications/source/unified-test-format/schema-1.1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "title": "Unified Test Format",
  "type": "object",
  "additionalProperties": false,
  "required": ["description", "schemaVersion", "tests"],
  "properties": {
    "description": { "type": "string" },
    "schemaVersion": { "$ref": "#/definitions/version" },
    "runOnRequirements": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/runOnRequirement" }
    },
    "createEntities": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/entity" }
    },
    "initialData": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/collectionData" }
    },
    "tests": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/test" }
    },
    "_yamlAnchors": {
      "type": "object",
      "additionalProperties": true
    }
  },

  "definitions": {
    "version": {
      "type": "string",
      "pattern": "^[0-9]+(\\.[0-9]+){1,2}$"
    },

    "runOnRequirement": {
      "type": "object",
      "additionalProperties": false,
      "minProperties": 1,
      "properties": {
        "maxServerVersion": { "$ref": "#/definitions/version" },
        "minServerVersion": { "$ref": "#/definitions/version" },
        "topologies": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "enum": ["single", "replicaset", "sharded", "sharded-replicaset"]
          }
        },
        "serverParameters": {
          "type": "object",
          "minProperties": 1
        }
      }
    },

    "entity": {
      "type": "object",
      "additionalProperties": false,
      "maxProperties": 1,
      "minProperties": 1,
      "properties": {
        "client": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id"],
          "properties": {
            "id": { "type": "string" },
            "uriOptions": { "type": "object" },
            "useMultipleMongoses": { "type": "boolean" },
            "observeEvents": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string",
                "enum": ["commandStartedEvent", "commandSucceededEvent", "commandFailedEvent"]
              }
            },
            "ignoreCommandMonitoringEvents": {
              "type": "array",
              "minItems": 1,
              "items": { "type": "string" }
            },
            "serverApi": { "$ref":  "#/definitions/serverApi" }
          }
        },
        "database": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "client", "databaseName"],
          "properties": {
            "id": { "type": "string" },
            "client": { "type": "string" },
            "databaseName": { "type": "string" },
            "databaseOptions": { "$ref": "#/definitions/collectionOrDatabaseOptions" }
          }
        },
        "collection": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "database", "collectionName"],
          "properties": {
            "id": { "type": "string" },
            "database": { "type": "string" },
            "collectionName": { "type": "string" },
            "collectionOptions": { "$ref": "#/definitions/collectionOrDatabaseOptions" }
          }
        },
        "session": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "client"],
          "properties": {
            "id": { "type": "string" },
            "client": { "type": "string" },
            "sessionOptions": { "type": "object" }
          }
        },
        "bucket": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "database"],
          "properties": {
            "id": { "type": "string" },
            "database": { "type": "string" },
            "bucketOptions": { "type": "object" }
          }
        },
        "stream": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "hexBytes"],
          "properties": {
            "id": { "type": "string" },
            "hexBytes": {
              "type": "string",
              "pattern": "^([0-9A-Fa-f]{2})*$"
            }
          }
        }
      }
    },

    "collectionData": {
      "type": "object",
      "additionalProperties": false,
      "required": ["collectionName", "databaseName", "documents"],
      "properties": {
        "collectionName": { "type": "string" },
        "databaseName": { "type": "string" },
        "documents": {
          "type": "array",
          "items": { "type": "object" }
        }
      }
    },

    "expectedEventsForClient": {
      "type": "object",
      "additionalProperties": false,
      "required": ["client", "events"],
      "properties": {
        "client": { "type": "string" },
        "events": {
          "type": "array",
          "items": { "$ref": "#/definitions/expectedEvent" }
        }
      }
    },

    "expectedEvent": {
      "type": "object",
      "additionalProperties": false,
      "maxProperties": 1,
      "minProperties": 1,
      "properties": {
        "commandStartedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "command": { "type": "object" },
            "commandName": { "type": "string" },
            "databaseName": { "type": "string" }
          }
        },
        "commandSucceededEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "reply": { "type": "object" },
            "commandName": { "type": "string" }
          }
        },
        "commandFailedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "commandName": { "type": "string" }
          }
        }
      }
    },

    "collectionOrDatabaseOptions": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "readConcern": { "type": "object" },
        "readPreference": { "type": "object" },
        "writeConcern": { "type": "object" }
      }
    },

    "serverApi": {
      "type": "object",
      "additionalProperties": false,
      "required": ["version"],
      "properties": {
        "version": { "type": "string" },
        "strict": { "type":  "boolean" },
        "deprecationErrors": { "type":  "boolean" }
      }
    },

    "operation": {
      "type": "object",
      "additionalProperties": false,
      "required": ["name", "object"],
      "properties": {
        "name": { "type": "string" },
        "object": { "type": "string" },
        "arguments": { "type": "object" },
        "expectError":  { "$ref": "#/definitions/expectedError" },
        "expectResult": {},
        "saveResultAsEntity": { "type": "string" }
      },
      "allOf": [
        { "not": { "required": ["expectError", "expectResult"] } },
        { "not": { "required": ["expectError", "saveResultAsEntity"] } }
      ]
    },

    "expectedError": {
      "type": "object",
      "additionalProperties": false,
      "minProperties": 1,
      "properties": {
        "isError": {
          "type": "boolean",
          "const": true
        },
        "isClientError": { "type": "boolean" },
        "errorContains": { "type": "string" },
        "errorCode": { "type": "integer" },
        "errorCodeName": { "type": "string" },
        "errorLabelsContain": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "errorLabelsOmit": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "expectResult": {}
      }
    },

    "test": {
      "type": "object",
      "additionalProperties": false,
      "required": ["description", "operations"],
      "properties": {
        "description": { "type": "string" },
        "runOnRequirements": {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#/definitions/runOnRequirement" }
        },
        "skipReason": { "type": "string" },
        "operations": {
          "type": "array",
          "items": { "$ref": "#/definitions/operation" }
        },
        "expectEvents": {
          "type": "array",
          "items": { "$ref": "#/definitions/expectedEventsForClient" }
        },
        "outcome": {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#/definitions/collectionData" }
        }
      }
    }
  }
}

=== mongodb/specifications/source/load-balancers/tests/uri-validation.json
{
  "description": "URI validation for load-balanced clusters",
  "schemaVersion": "1.4",
  "runOnRequirements": [
    {
      "topologies": [
        "single",
        "sharded"
      ]
    }
  ],
  "createEntities": [
    {
      "client": {
        "id": "regularClient",
        "useMultipleMongoses": false
      }
    },
    {
      "database": {
        "id": "regularDatabase",
        "client": "regularClient",
        "databaseName": "testdb"
      }
    }
  ],
  "tests": [
    {
      "description": "error when connection string contains multiple hosts with loadBalanced=true",
      "operations": [
        {
          "name": "createClient",
          "object": "testRunner",
          "arguments": {
            "clientOptions": {
              "uriOptions": {
                "loadBalanced": true
              },
              "uriHosts": [
                "localhost:27017",
                "localhost:27018"
              ]
            }
          },
          "expectError": {
            "errorContains": "cannot be used with multiple hosts"
          }
        }
      ]
    },
    {
      "description": "error when connection string contains replicaSet with loadBalanced=true",
      "operations": [
        {
          "name": "createClient",
          "object": "testRunner",
          "arguments": {
            "clientOptions": {
              "uriOptions": {
                "loadBalanced": true,
                "replicaSet": "mySet"
              }
            }
          },
          "expectError": {
            "errorContains": "cannot be used with replicaSet"
          }
        }
      ]
    },
    {
      "description": "error when connection string contains directConnection=true with loadBalanced=true",
      "operations": [
        {
          "name": "createClient",
          "object": "testRunner",
          "arguments": {
            "clientOptions": {
              "uriOptions": {
                "loadBalanced": true,
                "directConnection": true
              }
            }
          },
          "expectError": {
            "errorContains": "cannot be used with directConnection=true"
          }
        }
      ]
    },
    {
      "description": "error when connection string contains srvMaxHosts with loadBalanced=true",
      "operations": [
        {
          "name": "createClient",
          "object": "testRunner",
          "arguments": {
            "clientOptions": {
              "uriOptions": {
                "loadBalanced": true,
                "srvMaxHosts": 2
              }
            }
          },
          "expectError": {
            "errorContains": "cannot be used with srvMaxHosts"
          }
        }
      ]
    }
  ]
}

=== mongodb/specifications/source/crud/tests/unified/updateOne-hint-unacknowledged.json
{
  "description": "updateOne-hint-unacknowledged",
  "schemaVersion": "1.0",
  "createEntities": [
    {
      "client": {
        "id": "client0",
        "observeEvents": [
          "commandStartedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "db0"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "coll0",
        "collectionOptions": {
          "writeConcern": {
            "w": 0
          }
        }
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "coll0",
      "databaseName": "db0",
      "documents": [
        {
          "_id": 1,
          "x": 11
        },
        {
          "_id": 2,
          "x": 22
        }
      ]
    }
  ],
  "tests": [
    {
      "description": "Unacknowledged updateOne with hint string on 4.2+ server",
      "runOnRequirements": [
        {
          "minServerVersion": "4.2.0"
        }
      ],
      "operations": [
        {
          "object": "collection0",
          "name": "updateOne",
          "arguments": {
            "filter": {
              "_id": {
                "$gt": 1
              }
            },
            "update": {
              "$inc": {
                "x": 1
              }
            },
            "hint": "_id_"
          },
          "expectResult": {
            "$$unsetOrMatches": {
              "acknowledged": {
                "$$unsetOrMatches": false
              }
            }
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "update": "coll0",
                  "updates": [
                    {
                      "q": {
                        "_id": {
                          "$gt": 1
                        }
                      },
                      "u": {
                        "$inc": {
                          "x": 1
                        }
                      },
                      "multi": {
                        "$$unsetOrMatches": false
                      },
                      "upsert": {
                        "$$unsetOrMatches": false
                      },
                      "hint": {
                        "$$type": [
                          "string",
                          "object"
                        ]
                      }
                    }
                  ],
                  "writeConcern": {
                    "w": 0
                  }
                }
              }
            }
          ]
        }
      ]
    },
    {
      "description": "Unacknowledged updateOne with hint document on 4.2+ server",
      "runOnRequirements": [
        {
          "minServerVersion": "4.2.0"
        }
      ],
      "operations": [
        {
          "object": "collection0",
          "name": "updateOne",
          "arguments": {
            "filter": {
              "_id": {
                "$gt": 1
              }
            },
            "update": {
              "$inc": {
                "x": 1
              }
            },
            "hint": {
              "_id": 1
            }
          },
          "expectResult": {
            "$$unsetOrMatches": {
              "acknowledged": {
                "$$unsetOrMatches": false
              }
            }
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "update": "coll0",
                  "updates": [
                    {
                      "q": {
                        "_id": {
                          "$gt": 1
                        }
                      },
                      "u": {
                        "$inc": {
                          "x": 1
                        }
                      },
                      "multi": {
                        "$$unsetOrMatches": false
                      },
                      "upsert": {
                        "$$unsetOrMatches": false
                      },
                      "hint": {
                        "$$type": [
                          "string",
                          "object"
                        ]
                      }
                    }
                  ],
                  "writeConcern": {
                    "w": 0
                  }
                }
              }
            }
          ]
        }
      ]
    }
  ]
}

=== mongodb/specifications/source/collection-management/timeseries-collection.json
{
  "description": "timeseries-collection",
  "schemaVersion": "1.0",
  "runOnRequirements": [
    {
      "minServerVersion": "4.9",
      "serverParameters": {
        "featureFlagTimeseriesCollection": {
          "value": true,
          "version": "5.0"
        }
      }
    }
  ],
  "createEntities": [
    {
      "client": {
        "id": "client0",
        "observeEvents": [
          "commandStartedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "ts-tests"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "test"
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "test",
      "databaseName": "ts-tests",
      "documents": []
    }
  ],
  "tests": [
    {
      "description": "createCollection with all options",
      "operations": [
        {
          "name": "dropCollection",
          "object": "database0",
          "arguments": {
            "collection": "test"
          }
        },
        {
          "name": "createCollection",
          "object": "database0",
          "arguments": {
            "collection": "test",
            "timeseries": {
              "timeField": "time",
              "metaField": "meta",
              "expireAfterSeconds": 604800
            }
          }
        },
        {
          "name": "assertCollectionExists",
          "object": "testRunner",
          "arguments": {
            "databaseName": "ts-tests",
            "collectionName": "test"
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "drop": "test"
                },
                "commandName": "drop",
                "databaseName": "ts-tests"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "create": "test",
                  "timeseries": {
                    "timeField": "time",
                    "metaField": "meta",
                    "expireAfterSeconds": 604800
                  }
                },
                "commandName": "create",
                "databaseName": "ts-tests"
              }
            }
          ]
        }
      ]
    }
  ]
}

=== mongodb/specifications/source/crud/tests/unified/countDocuments-comment.json
{
  "description": "count",
  "schemaVersion": "1.0",
  "createEntities": [
    {
      "client": {
        "id": "client0",
        "useMultipleMongoses": false,
        "uriOptions": {
          "retryReads": false
        },
        "observeEvents": [
          "commandStartedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "count-test"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "coll0"
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "coll0",
      "databaseName": "count-test",
      "documents": [
        {
          "_id": 1,
          "x": 11
        },
        {
          "_id": 2,
          "x": 22
        },
        {
          "_id": 3,
          "x": 33
        }
      ]
    }
  ],
  "tests": [
    {
      "description": "count with comment on 4.4.0 or greater",
      "runOnRequirements": [
        {
          "minServerVersion": "4.4.0"
        }
      ],
      "operations": [
        {
          "name": "countDocuments",
          "object": "collection0",
          "arguments": {
            "filter": {},
            "comment": {
              "key": "value"
            }
          },
          "expectResult": 3
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "aggregate": "coll0",
                  "pipeline": [
                    {
                      "$match": {}
                    },
                    {
                      "$group": {
                        "_id": 1,
                        "n": {
                          "$sum": 1
                        }
                      }
                    }
                  ],
                  "comment": {
                    "key": "value"
                  }
                },
                "commandName": "aggregate",
                "databaseName": "count-test"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "count with comment on less than 4.4.0 - string comment",
      "runOnRequirements": [
        {
          "minServerVersion": "3.6.0",
          "maxServerVersion": "4.3.99"
        }
      ],
      "operations": [
        {
          "name": "countDocuments",
          "object": "collection0",
          "arguments": {
            "filter": {},
            "comment": "comment"
          },
          "expectResult": 3
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "aggregate": "coll0",
                  "pipeline": [
                    {
                      "$match": {}
                    },
                    {
                      "$group": {
                        "_id": 1,
                        "n": {
                          "$sum": 1
                        }
                      }
                    }
                  ],
                  "comment": "comment"
                },
                "commandName": "aggregate",
                "databaseName": "count-test"
              }
            }
          ]
        }
      ]
    }
  ]
}

=== mongodb/specifications/source/crud/tests/unified/find-comment.json
{
  "description": "find-comment",
  "schemaVersion": "1.0",
  "createEntities": [
    {
      "client": {
        "id": "client0",
        "observeEvents": [
          "commandStartedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "crud-tests"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "coll0"
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "coll0",
      "databaseName": "crud-tests",
      "documents": [
        {
          "_id": 1
        },
        {
          "_id": 2
        }
      ]
    }
  ],
  "tests": [
    {
      "description": "find with string comment",
      "operations": [
        {
          "name": "find",
          "object": "collection0",
          "arguments": {
            "filter": {
              "_id": 1
            },
            "comment": "comment"
          },
          "expectResult": [
            {
              "_id": 1
            }
          ]
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll0",
                  "filter": {
                    "_id": 1
                  },
                  "comment": "comment"
                }
              }
            }
          ]
        }
      ]
    },
    {
      "description": "find with document comment",
      "runOnRequirements": [
        {
          "minServerVersion": "4.4"
        }
      ],
      "operations": [
        {
          "name": "find",
          "object": "collection0",
          "arguments": {
            "filter": {
              "_id": 1
            },
            "comment": {
              "key": "value"
            }
          },
          "expectResult": [
            {
              "_id": 1
            }
          ]
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "coll0",
                  "filter": {
                    "_id": 1
                  },
                  "comment": {
                    "key": "value"
                  }
                }
              }
            }
          ]
        }
      ]
    },
    {
      "description": "find with document comment - pre 4.4",
      "runOnRequirements": [
        {
          "maxServerVersion": "4.2.99"
        }
      ],
      "operations": [
        {
          "name": "find",
          "object": "collection0",
          "arguments": {
            "filter": {
              "_id": 1
            },
            "comment": {
              "key": "value"
            }
          },
          "expectError": {
            "errorContains": "'comment' field must be of BSON type string",
            "isClientError": false
          }
        }
      ]
    }
  ]
}

=== mongodb/specifications/source/crud/tests/unified/estimatedDocumentCount-comment.json
{
  "description": "estimatedDocumentCount-comment",
  "schemaVersion": "1.0",
  "createEntities": [
    {
      "client": {
        "id": "client0",
        "observeEvents": [
          "commandStartedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "edc-tests"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "coll0"
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "coll0",
      "databaseName": "edc-tests",
      "documents": [
        {
          "_id": 1,
          "x": 11
        },
        {
          "_id": 2,
          "x": 22
        },
        {
          "_id": 3,
          "x": 33
        }
      ]
    }
  ],
  "tests": [
    {
      "description": "estimatedDocumentCount with document comment on 4.9.0 or greater",
      "runOnRequirements": [
        {
          "minServerVersion": "4.9.0"
        }
      ],
      "operations": [
        {
          "name": "estimatedDocumentCount",
          "object": "collection0",
          "arguments": {
            "comment": {
              "key": "value"
            }
          },
          "expectResult": 3
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "aggregate": "coll0",
                  "pipeline": [
                    {
                      "$collStats": {
                        "count": {}
                      }
                    },
                    {
                      "$group": {
                        "_id": 1,
                        "n": {
                          "$sum": "$count"
                        }
                      }
                    }
                  ],
                  "comment": {
                    "key": "value"
                  }
                },
                "commandName": "aggregate",
                "databaseName": "edc-tests"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "estimatedDocumentCount with document comment on less than 4.9.0",
      "runOnRequirements": [
        {
          "minServerVersion": "4.4.14",
          "maxServerVersion": "4.8.99"
        }
      ],
      "operations": [
        {
          "name": "estimatedDocumentCount",
          "object": "collection0",
          "arguments": {
            "comment": {
              "key": "value"
            }
          },
          "expectResult": 3
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "count": "coll0",
                  "comment": {
                    "key": "value"
                  }
                },
                "commandName": "count",
                "databaseName": "edc-tests"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "estimatedDocumentCount with string comment on less than 4.4.14",
      "runOnRequirements": [
        {
          "minServerVersion": "4.4.0",
          "maxServerVersion": "4.4.13"
        }
      ],
      "operations": [
        {
          "name": "estimatedDocumentCount",
          "object": "collection0",
          "arguments": {
            "comment": "comment"
          },
          "expectResult": 3
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "count": "coll0",
                  "comment": "comment"
                },
                "commandName": "count",
                "databaseName": "edc-tests"
              }
            }
          ]
        }
      ]
    }
  ]
}
