=== mongodb/specifications/source/unified-test-format/schema-1.3.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "title": "Unified Test Format",
  "type": "object",
  "additionalProperties": false,
  "required": ["description", "schemaVersion", "tests"],
  "properties": {
    "description": { "type": "string" },
    "schemaVersion": { "$ref": "#/definitions/version" },
    "runOnRequirements": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/runOnRequirement" }
    },
    "createEntities": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/entity" }
    },
    "initialData": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/collectionData" }
    },
    "tests": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/definitions/test" }
    },
    "_yamlAnchors": {
      "type": "object",
      "additionalProperties": true
    }
  },

  "definitions": {
    "version": {
      "type": "string",
      "pattern": "^[0-9]+(\\.[0-9]+){1,2}$"
    },

    "runOnRequirement": {
      "type": "object",
      "additionalProperties": false,
      "minProperties": 1,
      "properties": {
        "maxServerVersion": { "$ref": "#/definitions/version" },
        "minServerVersion": { "$ref": "#/definitions/version" },
        "topologies": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "enum": ["single", "replicaset", "sharded", "sharded-replicaset", "load-balanced"]
          }
        },
        "serverParameters": {
          "type": "object",
          "minProperties": 1
        },
        "auth": { "type": "boolean" }
      }
    },

    "entity": {
      "type": "object",
      "additionalProperties": false,
      "maxProperties": 1,
      "minProperties": 1,
      "properties": {
        "client": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id"],
          "properties": {
            "id": { "type": "string" },
            "uriOptions": { "type": "object" },
            "useMultipleMongoses": { "type": "boolean" },
            "observeEvents": {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string",
                "enum": [
                  "commandStartedEvent",
                  "commandSucceededEvent",
                  "commandFailedEvent",
                  "poolCreatedEvent",
                  "poolReadyEvent",
                  "poolClearedEvent",
                  "poolClosedEvent",
                  "connectionCreatedEvent",
                  "connectionReadyEvent",
                  "connectionClosedEvent",
                  "connectionCheckOutStartedEvent",
                  "connectionCheckOutFailedEvent",
                  "connectionCheckedOutEvent",
                  "connectionCheckedInEvent"
                ]
              }
            },
            "ignoreCommandMonitoringEvents": {
              "type": "array",
              "minItems": 1,
              "items": { "type": "string" }
            },
            "storeEventsAsEntities": {
              "type": "array",
              "minItems": 1,
              "items": { "$ref": "#/definitions/storeEventsAsEntity" }
            },
            "serverApi": { "$ref":  "#/definitions/serverApi" }
          }
        },
        "database": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "client", "databaseName"],
          "properties": {
            "id": { "type": "string" },
            "client": { "type": "string" },
            "databaseName": { "type": "string" },
            "databaseOptions": { "$ref": "#/definitions/collectionOrDatabaseOptions" }
          }
        },
        "collection": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "database", "collectionName"],
          "properties": {
            "id": { "type": "string" },
            "database": { "type": "string" },
            "collectionName": { "type": "string" },
            "collectionOptions": { "$ref": "#/definitions/collectionOrDatabaseOptions" }
          }
        },
        "session": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "client"],
          "properties": {
            "id": { "type": "string" },
            "client": { "type": "string" },
            "sessionOptions": { "type": "object" }
          }
        },
        "bucket": {
          "type": "object",
          "additionalProperties": false,
          "required": ["id", "database"],
          "properties": {
            "id": { "type": "string" },
            "database": { "type": "string" },
            "bucketOptions": { "type": "object" }
          }
        }
      }
    },

    "storeEventsAsEntity": {
      "type": "object",
      "additionalProperties": false,
      "required": ["id", "events"],
      "properties": {
        "id": { "type": "string" },
        "events": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "enum": [
              "PoolCreatedEvent",
              "PoolReadyEvent",
              "PoolClearedEvent",
              "PoolClosedEvent",
              "ConnectionCreatedEvent",
              "ConnectionReadyEvent",
              "ConnectionClosedEvent",
              "ConnectionCheckOutStartedEvent",
              "ConnectionCheckOutFailedEvent",
              "ConnectionCheckedOutEvent",
              "ConnectionCheckedInEvent",
              "CommandStartedEvent",
              "CommandSucceededEvent",
              "CommandFailedEvent"
            ]
          }
        }
      }
    },

    "collectionData": {
      "type": "object",
      "additionalProperties": false,
      "required": ["collectionName", "databaseName", "documents"],
      "properties": {
        "collectionName": { "type": "string" },
        "databaseName": { "type": "string" },
        "documents": {
          "type": "array",
          "items": { "type": "object" }
        }
      }
    },

    "expectedEventsForClient": {
      "type": "object",
      "additionalProperties": false,
      "required": ["client", "events"],
      "properties": {
        "client": { "type": "string" },
        "eventType": {
          "type": "string",
          "enum": ["command", "cmap"]
        },
        "events": { "type": "array" }
      },
      "oneOf": [
        {
          "required": ["eventType"],
          "properties": {
            "eventType": { "const": "command" },
            "events": {
              "type": "array",
              "items": { "$ref": "#/definitions/expectedCommandEvent" }
            }
          }
        },
        {
          "required": ["eventType"],
          "properties": {
            "eventType": { "const": "cmap" },
            "events": {
              "type": "array",
              "items": { "$ref": "#/definitions/expectedCmapEvent" }
            }
          }
        },
        {
          "additionalProperties": false,
          "properties": {
            "client": { "type": "string" },
            "events": {
              "type": "array",
              "items": { "$ref": "#/definitions/expectedCommandEvent" }
            }
          }
        }
      ]
    },

    "expectedCommandEvent": {
      "type": "object",
      "additionalProperties": false,
      "maxProperties": 1,
      "minProperties": 1,
      "properties": {
        "commandStartedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "command": { "type": "object" },
            "commandName": { "type": "string" },
            "databaseName": { "type": "string" },
            "hasServiceId": { "type": "boolean" }
          }
        },
        "commandSucceededEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "reply": { "type": "object" },
            "commandName": { "type": "string" },
            "hasServiceId": { "type": "boolean" }
          }
        },
        "commandFailedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "commandName": { "type": "string" },
            "hasServiceId": { "type": "boolean" }
          }
        }
      }
    },

    "expectedCmapEvent": {
      "type": "object",
      "additionalProperties": false,
      "maxProperties": 1,
      "minProperties": 1,
      "properties": {
        "poolCreatedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {}
        },
        "poolReadyEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {}
        },
        "poolClearedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "hasServiceId": { "type": "boolean" }
          }
        },
        "poolClosedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {}
        },
        "connectionCreatedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {}
        },
        "connectionReadyEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {}
        },
        "connectionClosedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "reason": { "type": "string" }
          }
        },
        "connectionCheckOutStartedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {}
        },
        "connectionCheckOutFailedEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "reason": { "type": "string" }
          }
        },
        "connectionCheckedOutEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {}
        },
        "connectionCheckedInEvent": {
          "type": "object",
          "additionalProperties": false,
          "properties": {}
        }
      }
    },

    "collectionOrDatabaseOptions": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "readConcern": { "type": "object" },
        "readPreference": { "type": "object" },
        "writeConcern": { "type": "object" }
      }
    },

    "serverApi": {
      "type": "object",
      "additionalProperties": false,
      "required": ["version"],
      "properties": {
        "version": { "type": "string" },
        "strict": { "type":  "boolean" },
        "deprecationErrors": { "type":  "boolean" }
      }
    },

    "operation": {
      "type": "object",
      "additionalProperties": false,
      "required": ["name", "object"],
      "properties": {
        "name": { "type": "string" },
        "object": { "type": "string" },
        "arguments": { "type": "object" },
        "ignoreResultAndError": { "type": "boolean" },
        "expectError":  { "$ref": "#/definitions/expectedError" },
        "expectResult": {},
        "saveResultAsEntity": { "type": "string" }
      },
      "allOf": [
        { "not": { "required": ["expectError", "expectResult"] } },
        { "not": { "required": ["expectError", "saveResultAsEntity"] } },
        { "not": { "required": ["ignoreResultAndError", "expectResult"] } },
        { "not": { "required": ["ignoreResultAndError", "expectError"] } },
        { "not": { "required": ["ignoreResultAndError", "saveResultAsEntity"] } }
      ]
    },

    "expectedError": {
      "type": "object",
      "additionalProperties": false,
      "minProperties": 1,
      "properties": {
        "isError": {
          "type": "boolean",
          "const": true
        },
        "isClientError": { "type": "boolean" },
        "errorContains": { "type": "string" },
        "errorCode": { "type": "integer" },
        "errorCodeName": { "type": "string" },
        "errorLabelsContain": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "errorLabelsOmit": {
          "type": "array",
          "minItems": 1,
          "items": { "type": "string" }
        },
        "expectResult": {}
      }
    },

    "test": {
      "type": "object",
      "additionalProperties": false,
      "required": ["description", "operations"],
      "properties": {
        "description": { "type": "string" },
        "runOnRequirements": {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#/definitions/runOnRequirement" }
        },
        "skipReason": { "type": "string" },
        "operations": {
          "type": "array",
          "items": { "$ref": "#/definitions/operation" }
        },
        "expectEvents": {
          "type": "array",
          "items": { "$ref": "#/definitions/expectedEventsForClient" }
        },
        "outcome": {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#/definitions/collectionData" }
        }
      }
    }
  }
}

=== mongodb/specifications/source/transactions-convenient-api/tests/unified/callback-aborts.json
{
  "description": "callback-aborts",
  "schemaVersion": "1.3",
  "runOnRequirements": [
    {
      "minServerVersion": "4.0",
      "topologies": [
        "replicaset"
      ]
    },
    {
      "minServerVersion": "4.1.8",
      "topologies": [
        "sharded",
        "load-balanced"
      ]
    }
  ],
  "createEntities": [
    {
      "client": {
        "id": "client0",
        "useMultipleMongoses": true,
        "observeEvents": [
          "commandStartedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "withTransaction-tests"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "test"
      }
    },
    {
      "session": {
        "id": "session0",
        "client": "client0"
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "test",
      "databaseName": "withTransaction-tests",
      "documents": []
    }
  ],
  "tests": [
    {
      "description": "withTransaction succeeds if callback aborts",
      "operations": [
        {
          "name": "withTransaction",
          "object": "session0",
          "arguments": {
            "callback": [
              {
                "name": "insertOne",
                "object": "collection0",
                "arguments": {
                  "session": "session0",
                  "document": {
                    "_id": 1
                  }
                },
                "expectResult": {
                  "$$unsetOrMatches": {
                    "insertedId": {
                      "$$unsetOrMatches": 1
                    }
                  }
                }
              },
              {
                "name": "abortTransaction",
                "object": "session0"
              }
            ]
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "insert": "test",
                  "documents": [
                    {
                      "_id": 1
                    }
                  ],
                  "ordered": true,
                  "lsid": {
                    "$$sessionLsid": "session0"
                  },
                  "txnNumber": {
                    "$numberLong": "1"
                  },
                  "startTransaction": true,
                  "autocommit": false,
                  "readConcern": {
                    "$$exists": false
                  },
                  "writeConcern": {
                    "$$exists": false
                  }
                },
                "commandName": "insert",
                "databaseName": "withTransaction-tests"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "abortTransaction": 1,
                  "lsid": {
                    "$$sessionLsid": "session0"
                  },
                  "txnNumber": {
                    "$numberLong": "1"
                  },
                  "autocommit": false,
                  "readConcern": {
                    "$$exists": false
                  },
                  "startTransaction": {
                    "$$exists": false
                  },
                  "writeConcern": {
                    "$$exists": false
                  }
                },
                "commandName": "abortTransaction",
                "databaseName": "admin"
              }
            }
          ]
        }
      ],
      "outcome": [
        {
          "collectionName": "test",
          "databaseName": "withTransaction-tests",
          "documents": []
        }
      ]
    },
    {
      "description": "withTransaction succeeds if callback aborts with no ops",
      "operations": [
        {
          "name": "withTransaction",
          "object": "session0",
          "arguments": {
            "callback": [
              {
                "name": "abortTransaction",
                "object": "session0"
              }
            ]
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": []
        }
      ],
      "outcome": [
        {
          "collectionName": "test",
          "databaseName": "withTransaction-tests",
          "documents": []
        }
      ]
    },
    {
      "description": "withTransaction still succeeds if callback aborts and runs extra op",
      "operations": [
        {
          "name": "withTransaction",
          "object": "session0",
          "arguments": {
            "callback": [
              {
                "name": "insertOne",
                "object": "collection0",
                "arguments": {
                  "session": "session0",
                  "document": {
                    "_id": 1
                  }
                },
                "expectResult": {
                  "$$unsetOrMatches": {
                    "insertedId": {
                      "$$unsetOrMatches": 1
                    }
                  }
                }
              },
              {
                "name": "abortTransaction",
                "object": "session0"
              },
              {
                "name": "insertOne",
                "object": "collection0",
                "arguments": {
                  "session": "session0",
                  "document": {
                    "_id": 2
                  }
                },
                "expectResult": {
                  "$$unsetOrMatches": {
                    "insertedId": {
                      "$$unsetOrMatches": 2
                    }
                  }
                }
              }
            ]
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "insert": "test",
                  "documents": [
                    {
                      "_id": 1
                    }
                  ],
                  "ordered": true,
                  "lsid": {
                    "$$sessionLsid": "session0"
                  },
                  "txnNumber": {
                    "$numberLong": "1"
                  },
                  "startTransaction": true,
                  "autocommit": false,
                  "readConcern": {
                    "$$exists": false
                  },
                  "writeConcern": {
                    "$$exists": false
                  }
                },
                "commandName": "insert",
                "databaseName": "withTransaction-tests"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "abortTransaction": 1,
                  "lsid": {
                    "$$sessionLsid": "session0"
                  },
                  "txnNumber": {
                    "$numberLong": "1"
                  },
                  "autocommit": false,
                  "readConcern": {
                    "$$exists": false
                  },
                  "startTransaction": {
                    "$$exists": false
                  },
                  "writeConcern": {
                    "$$exists": false
                  }
                },
                "commandName": "abortTransaction",
                "databaseName": "admin"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "insert": "test",
                  "documents": [
                    {
                      "_id": 2
                    }
                  ],
                  "ordered": true,
                  "lsid": {
                    "$$sessionLsid": "session0"
                  },
                  "readConcern": {
                    "afterClusterTime": {
                      "$$exists": true
                    }
                  },
                  "autocommit": {
                    "$$exists": false
                  },
                  "startTransaction": {
                    "$$exists": false
                  },
                  "writeConcern": {
                    "$$exists": false
                  }
                },
                "commandName": "insert",
                "databaseName": "withTransaction-tests"
              }
            }
          ]
        }
      ],
      "outcome": [
        {
          "collectionName": "test",
          "databaseName": "withTransaction-tests",
          "documents": [
            {
              "_id": 2
            }
          ]
        }
      ]
    }
  ]
}

=== mongodb/specifications/source/retryable-writes/tests/unified/handshakeError.json
{
  "description": "retryable writes handshake failures",
  "schemaVersion": "1.3",
  "runOnRequirements": [
    {
      "minServerVersion": "4.2",
      "topologies": [
        "replicaset",
        "sharded",
        "load-balanced"
      ],
      "auth": true
    }
  ],
  "createEntities": [
    {
      "client": {
        "id": "client0",
        "useMultipleMongoses": false,
        "observeEvents": [
          "commandStartedEvent",
          "connectionCheckOutStartedEvent"
        ],
        "uriOptions": {
          "retryReads": true,
          "retryWrites": true,
          "maxPoolSize": 5
        }
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "retryable-handshake-tests"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "coll"
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "coll",
      "databaseName": "retryable-handshake-tests",
      "documents": [
        {
          "_id": 1,
          "x": 11
        }
      ]
    }
  ],
  "tests": [
    {
      "description": "InsertOne succeeds after retryable handshake error",
      "operations": [
        {
          "name": "failPoint",
          "object": "testRunner",
          "arguments": {
            "client": "client0",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 1
              },
              "data": {
                "failCommands": [
                  "saslContinue"
                ],
                "closeConnection": true
              }
            }
          }
        },
        {
          "name": "insertOne",
          "object": "collection0",
          "arguments": {
            "document": {
              "_id": 2,
              "x": 22
            }
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "eventType": "cmap",
          "events": [
            {
              "connectionCheckOutStartedEvent": {}
            },
            {
              "connectionCheckOutStartedEvent": {}
            }
          ]
        },
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "insert": "coll",
                  "documents": [
                    {
                      "_id": 2,
                      "x": 22
                    }
                  ]
                },
                "commandName": "insert",
                "databaseName": "retryable-handshake-tests"
              }
            }
          ]
        }
      ],
      "outcome": [
        {
          "collectionName": "coll",
          "databaseName": "retryable-handshake-tests",
          "documents": [
            {
              "_id": 1,
              "x": 11
            },
            {
              "_id": 2,
              "x": 22
            }
          ]
        }
      ]
    }
  ]
}

=== mongodb/specifications/source/causal-consistency/tests/causal-consistency-clientBulkWrite.json
{
  "description": "causal consistency write commands include afterClusterTime",
  "schemaVersion": "1.3",
  "runOnRequirements": [
    {
      "minServerVersion": "8.0",
      "topologies": [
        "replicaset",
        "sharded",
        "load-balanced"
      ]
    }
  ],
  "createEntities": [
    {
      "client": {
        "id": "client0",
        "useMultipleMongoses": false,
        "uriOptions": {
          "retryWrites": false
        },
        "observeEvents": [
          "commandStartedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "causal-consistency-tests"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "test"
      }
    },
    {
      "session": {
        "id": "session0",
        "client": "client0",
        "sessionOptions": {
          "causalConsistency": true
        }
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "test",
      "databaseName": "causal-consistency-tests",
      "documents": [
        {
          "_id": 1,
          "x": 11
        },
        {
          "_id": 2,
          "x": 22
        },
        {
          "_id": 3,
          "x": 33
        }
      ]
    }
  ],
  "tests": [
    {
      "description": "clientBulkWrite includes afterClusterTime in causally consistent session",
      "operations": [
        {
          "name": "find",
          "object": "collection0",
          "arguments": {
            "session": "session0",
            "filter": {
              "_id": 1
            }
          },
          "expectResult": [
            {
              "_id": 1,
              "x": 11
            }
          ]
        },
        {
          "name": "clientBulkWrite",
          "object": "client0",
          "arguments": {
            "session": "session0",
            "models": [
              {
                "insertOne": {
                  "namespace": "causal-consistency-tests.test",
                  "document": {
                    "_id": 4
                  }
                }
              }
            ]
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "commandName": "find",
                "command": {
                  "find": "test",
                  "readConcern": {
                    "$$exists": false
                  },
                  "lsid": {
                    "$$sessionLsid": "session0"
                  }
                }
              }
            },
            {
              "commandStartedEvent": {
                "commandName": "bulkWrite",
                "command": {
                  "bulkWrite": 1,
                  "lsid": {
                    "$$sessionLsid": "session0"
                  },
                  "readConcern": {
                    "afterClusterTime": {
                      "$$exists": true
                    },
                    "level": {
                      "$$exists": false
                    }
                  }
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
